# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Event

# Model Form Field configuration
form: $/stu177/events/models/event/fields.yaml

# Model Class name
modelClass: Stu177\Events\Models\Event

# Default redirect location
defaultRedirect: stu177/events/events

# Create page
create:
    title: Create Event
    redirect: stu177/events/events/update/:id
    redirectClose: stu177/events/events

# Update page
update:
    title: Edit Event
    redirect: stu177/events/events
    redirectClose: stu177/events/events

# Preview page
preview:
    title: Preview Event